spring:
  cloud:
    gateway:
      routes:
        - id: WORKFLOW-CONFIGURATION-SERVICE
          uri: WORKFLOW-CONFIGURATION-SERVICE
          predicates:
            - Path=/config/**
        - id: WORKFLOW-INITIATOR
          uri: WORKFLOW-INITIATOR
          predicates:
            - Path=/init/**