management:
  tracing:
    sampling:
      probability: 1.0 # sampling all in dev, reduce it in prod to save loading
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#spring:
#  kafka:
#    consumer:
#      auto-offset-reset: earliest
#      bootstrap-servers: kafka:9092
#      group-id: group-default
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            value:
#              default:
#                type: 'com.workflow.WorkflowInitiator.kafka.consumer.MyEvent'
#            type:
#              mapping: 'com.workflow.WorkflowConfigurationService.kafka.producer.MyEvent:com.workflow.WorkflowInitiator.kafka.consumer.MyEvent'
#            trusted:
#              packages: 'com.workflow.WorkflowConfigurationService.kafka.producer'
#    producer:
#      acks: -1
#      bootstrap-servers: kafka:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer